// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Symphony.Infrastructure.Persistence.Sqlite;

#nullable disable

namespace Symphony.Infrastructure.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SymphonyDbContext))]
    [Migration("20260311002714_MultiTurnSessions")]
    partial class MultiTurnSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.DispatchClaimEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedByInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("Status");

                    b.HasIndex("IssueId", "Status");

                    b.ToTable("dispatch_claims", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.EventLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunAttemptId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("RunId");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.InstanceLeaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaseName")
                        .IsUnique();

                    b.ToTable("instance_leases", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.IssueCacheEntity", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedByJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CachedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Milestone")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.HasIndex("Identifier");

                    b.HasIndex("State");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("issues_cache", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.RetryQueueEntity", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DelayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBackoffMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.HasIndex("Attempt");

                    b.HasIndex("DueAtUtc");

                    b.ToTable("retry_queue", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.RunAttemptEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("run_attempts", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.RunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CleanupWorkspaceOnStop")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentRetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEvent")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastEventAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastReportedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportedTotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedStopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("State");

                    b.HasIndex("Status");

                    b.HasIndex("IssueId", "Status")
                        .IsUnique()
                        .HasFilter("Status IN ('running', 'retrying')");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodexAppServerPid")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodexInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodexOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodexTotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCodexEvent")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCodexMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCodexTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastReportedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReportedTotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunAttemptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurnId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastCodexTimestamp");

                    b.HasIndex("RunAttemptId");

                    b.HasIndex("RunId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.WorkflowSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LoadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigHash");

                    b.HasIndex("LoadedAtUtc");

                    b.ToTable("workflow_snapshots", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.WorkspaceRecordEntity", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCleanedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCleanupReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastPreparedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.HasIndex("IssueIdentifier");

                    b.ToTable("workspace_records", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.RunAttemptEntity", b =>
                {
                    b.HasOne("Symphony.Infrastructure.Persistence.Sqlite.Entities.RunEntity", "Run")
                        .WithMany("Attempts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.RunEntity", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
