// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Symphony.Infrastructure.Persistence.Sqlite;

#nullable disable

namespace Symphony.Infrastructure.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SymphonyDbContext))]
    [Migration("20260305052641_LeaseClaimUniqueActive")]
    partial class LeaseClaimUniqueActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.DispatchClaimEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedByInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("Status");

                    b.HasIndex("IssueId", "Status");

                    b.ToTable("dispatch_claims", (string)null);
                });

            modelBuilder.Entity("Symphony.Infrastructure.Persistence.Sqlite.Entities.InstanceLeaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaseName")
                        .IsUnique();

                    b.ToTable("instance_leases", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
